---
title: "Replication of Study Black and White Lies:Race-Based Biases in Deception Judgements (2017, Psychological Science)"
author: "E. Paige Lloyd, Kurt Hugenberg, Allen R. McConnel, Jonathan W. Kunstman, & Jason C. Deska"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

I am interested in understanding and correcting biases, especially in the context of social groups. This paper by Lloyd, Hugenberg, McConnel, Kunstman, & Deska (2017) examines the truth bias by understanding how group membership influences perceivers decisions on whether an individual is seen as deceiving or truthful. I plan to replication Study 1c, which found that White American participants used the truth response more for Black targets than for White targets. The paper also used the Open Science Framework, making it relatively easy to replicate. 

Participants will be viewing one of two sets of 40 deception-judgement videos that are provided by the author. Each video will show an individual telling a story, and participants will determine whether the individual is lying or not. They will also be completing Plant and Devine's (1998) Internal and External Motivation to Respond Without Prejudice measure, Glaser and Knowles's (2008) Implicit Motivation to Control Prejudice task, and Kunstman et al. (2013) 17-item intergroup contact measure. Because I am not very familiar with amazon mechanical turk, I am expecting to have a some challenges within making sure that the stimuli will be represented correctly, without errors within the survey flow. Because I have not done statistical analysis for a while, I also expect some challenges within the data analysis bit. Fortunately, because the study is on OSF, I hope that it would be relatively easier to learn. 

####Repository
https://github.com/sakaria4/lloyd2017.git

####Original paper
https://github.com/sakaria4/lloyd2017/tree/master/original_paper




##Methods

###Power Analysis

According to Lloyd et al.(2017), an a priori power analysis indicated that 67 participants are needed to achieve 80% power for the analysis. 

###Planned Sample

67 White Americans

###Materials

- MU3D Videos
- Plant and Devine's (1998) Internal and External Motivation to Respond Without Prejudice measure
- Glaser and Knowles's (2008) Implicit Motivation to Control Prejudice task
- Kunstman et al. (2013) 17-item intergroup contact measure.


###Procedure	

Participants were randomly assigned to view one of two sets of 40 deception-judgment videos (Lloyd et al., 2017; for details on the development of the stimuli, see the Supplemental Material). Videos featured Black and White college-age individuals describing acquaintances; each set of videos featured 20 positive descriptions and 20 negative descriptions, and valence was balanced across race. Participants saw each target person twice, once when the target was lying and once when the target was telling the truth. Within each set, videos were presented in random order. After each video, participants provided a truth/lie judgment, and they had an unlimited amount of time to respond. Participants were instructed that they might see the same individual multiple times but that they should base their judgments only on the current video because some individuals might tell only lies, some might tell only truths, and some might tell a combination of truths and lies. Participants completed the deception judgment task in addition to the IMS (M = 7.59, SD = 1.42, a = .86) and EMS (M = 4.77, SD = 1.60, a = .77). The only modification in the current study was that participants completed a 10-item measure assessing interpersonal contact both with Whites and with Blacks. Participants responded to each item on a 10-point scale with anchors of 0 and 9 or more (e.g., "How many Black [White] friends do you have in college?"; mean number of White contacts = 8.06, SD = 2.15, a= .85; mean number of Black contacts = 3.43, SD = 1.88, a = .76; adapted from Kunstman et al., 2013). Number of Black contacts, number of White contacts,  and the difference between them (i.e., White contacts minus Black contacts) did not moderate the findings
reported (ps > .130).

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
